- name: Calculate file paths
  set_fact:
    dl_cache: /var/tmp/import_lxc_from_artifact/{{ lxc_name }}
    archive_file: /var/tmp/import_lxc_from_artifact/{{ lxc_name }}/{{ lxc_name }}.tar.gz
    zip_dest: /var/tmp/import_lxc_from_artifact/{{ lxc_name }}/lxc-artifact.zip

- name: Create working directory
  ansible.builtin.file:
    path: "{{ vars.dl_cache }}"
    state: directory
    recurse: yes

- name: Download nightly of the LXC image
  ansible.builtin.get_url:
    url: "{{ lxc_zip_url }}"
    dest: "{{ vars.zip_dest }}"

- name: Extract image archive out of zip file
  ansible.builtin.unarchive:
    remote_src: yes 
    src: "{{ vars.zip_dest }}"
    dest: "{{ vars.dl_cache }}"

- name: Get stats of the extracted artifact
  ansible.builtin.stat:
    path: "{{ vars.archive_file }}"
  register: st

- name: Fail if the expected archive name was not created
  ansible.builtin.fail:
    msg: "The artifact from {{ lxc_zip_url }} did not contain a {{ lxc_name }}.tar.gz!"
  when: not st.stat.isreg 

- name: Delete existing image 
  shell: lxc image delete {{ lxc_name }}
  ignore_errors: yes

- name: Import image into LXC
  shell: lxc image import --alias={{ lxc_name }} {{ vars.archive_file }}
