apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
nameSuffix: ""
configMapGenerator:
  - name: fluentd-conf
    files:
      - configs/fluentd.conf
generatorOptions:
  disableNameSuffixHash: true
