apiVersion: v1
kind: Namespace
metadata:
  name: homer
---
apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  selector:
    app: homer
  ports:
    - port: 80
      targetPort: 8080
      appProtocol: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer
  labels:
    name: homer
spec:
  rules:
    - host: s.astrid.tech
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: homer
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: b4bz/homer
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /www/assets
              name: assets
      volumes:
        - name: assets
          configMap:
            name: homer-assets
