apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homer
commonLabels:
  app: homer
configMapGenerator:
  - name: homer-assets
    files:
      - assets/config.yml
      - assets/grafana.svg
      - assets/freeipa.png
      #- assets/proxmox.png
      - assets/jupyter.png
      - assets/utorrent.svg
      - assets/kubernetes.png
      - assets/firefly.png
      - assets/elabftw.webp
      - assets/spark.svg
      - assets/longhorn.png
resources:
  - homer.yaml
