#cloud-config
ssh_pwauth: false
users:
  - name: ansible
    gecos: Ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMh9bjqeopX/MELieVU+HqhlvZi84BTr4qjnDRuOST1I astrid@banana
  - name: astrid
    gecos: Astrid Yu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMh9bjqeopX/MELieVU+HqhlvZi84BTr4qjnDRuOST1I astrid@banana
  - name: alia
    gecos: Alia Lescoulie
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGrjRIMgZlNU1Jq1+xiN+bSUNfZDq+LHQrQTLrh3DW0R alia@Alias-MBP
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6yiGNluxprmAWry7VMhM7C4URicoRKOUsdeZkbOxUefGtlXTuyD+DmoaCc7FLt8vYFySPYmwduz+2hJBVdP1rmNlFZ4OEzqKGIsExfJwrOH3Q/7jCLy1fmZT1DMGrG8bKxx6O7axsvMx4XE9hT0v72W+owHpeBjtYSGh2NUFFcFcDwxXh2oFcQVCW4krnTAKi4gEAjusnCW2T9vYxsks8NMaJ7Hx/M48eyuK4XELvSrL3oxgbAevaW/wvaFHobDs5TWuPzVufdev6pfIsi6Th3B5OPktYeSPY8c8d7mgQ1BeahzvxLBi1bDOFZVSym9id4wyY6e0VwvoHkE5Un7WLsG7dr99PIgsSDfxrH3BJyhrYcT+8E2qTMFM3tz1pa4htVkaLEJ/ti4mFwqgdyvhm05BfrAlczk66sobohGw4PGgvUfGGpNen7yDRk89yfm63tWor+HepQt2Zri1fDDZGtncewR3SZq7af6wOPk3O47vLyJwA4DGpZ99rsFgUp9M= alia@Alias-MBP-2
runcmd:
  - dnf install -y epel-release
  - dnf install -y ansible-core build-essential firewalld less neofetch neovim tar tmux tree wget
  - systemctl enable firewalld && systemctl start firewalld
  - curl -s https://install.zerotier.com | bash
  - zerotier-cli join e5cd7a9e1c618388
