#cloud-config
ssh_pwauth: false
hostname: ipa0.id.astrid.tech
users:
  - name: ansible
    gecos: Ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9VBBdNd2mdO493CU+Tg0idjTR679V1UV2I3LVwh+hH astrid@gfdesk
  - name: astrid
    gecos: Astrid Yu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9VBBdNd2mdO493CU+Tg0idjTR679V1UV2I3LVwh+hH astrid@gfdesk
write_files:
- path: /etc/sysconfig/network-scripts/ifcfg-eth0
  content: |
    NAME=eth0
    DEVICE=eth0
    BOOTPROTO=none
    ONBOOT=yes
    IPADDR=192.168.1.5
    PREFIX=24
    IPV6INIT=yes
    IPV6ADDR=fd53:1de8:470a::5:1/64
    GATEWAY=192.168.1.1
    DNS1=8.8.8.8
    DNS2=8.8.4.4
    TYPE=Ethernet
runcmd:
  - dnf module enable -y idm:DL1
  - dnf install -y epel-release
  - dnf install -y ansible firewalld freeipa-server freeipa-server-dns less tmux
  - systemctl enable firewalld && systemctl start firewalld
  - curl -s https://install.zerotier.com | bash
    # - zerotier-cli join b6079f73c67cda0d
  - sudo reboot

