#cloud-config
ssh_pwauth: false
fdqn: ipa0.id.astrid.tech

users:
  - name: ansible
    gecos: Ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9VBBdNd2mdO493CU+Tg0idjTR679V1UV2I3LVwh+hH astrid@gfdesk
  - name: astrid
    gecos: Astrid Yu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9VBBdNd2mdO493CU+Tg0idjTR679V1UV2I3LVwh+hH astrid@gfdesk
packages: 
  - ansible-core
  - firewalld
  - freeipa-server
  - freeipa-server-dns
  - less
  - tmux
runcmd:
  - systemctl enable firewalld && systemctl start firewalld
  - curl -s https://install.zerotier.com | bash

