version: "3.7"
services:
  webmentions:
    image: ghcr.io/astralbijection/wm-receiver:main
    hostname: wm_receiver
    expose:
      - 8000
    environment:
      DATABASE_URL: /app/data/data.db
      ALLOWED_TARGET_HOSTS: astrid.tech,aay.tw
      WEBMENTION_SUBDIR: content/webmentions
      REPO_DIR: ./repo
      REMOTE_URL: "git@github.com:astralbijection/astrid.tech.git"
      BRANCH_NAME: auto/webmention
      BASE_BRANCH: main
      ROCKET_ADDRESS: "0.0.0.0"
      SSH_PRIVATE_KEY_FILE: /app/id_rsa
      GIT_NAME: Webmention Receiver
      GIT_EMAIL: editor@astrid.tech
    volumes:
      # folder mount, containing DB, that the app can auto-create
      - ./data:/app/data
      - ./known_hosts:/root/.ssh/known_hosts
      - ./id_rsa:/app/id_rsa
    restart: always
    networks:
      - proxied

networks:
  proxied:
    external:
      name: proxied
