version: "3.7"
services:
  webmentions:
    image: ghcr.io/astridyu/wm-receiver:main
    hostname: wm_receiver
    expose:
      - 8000
    environment:
      ALLOWED_TARGET_HOSTS: astrid.tech,aay.tw
      WEBMENTION_SUBDIR: content/webmentions
      REMOTE_URL: "git@github.com:astridyu/astrid.tech.git"
      BRANCH_NAME: auto/webmention
      BASE_BRANCH: main
      ROCKET_ADDRESS: "0.0.0.0"
      GIT_NAME: Webmention Receiver
      GIT_EMAIL: editor@astrid.tech
    volumes:
      - ./data:/app/data
      - ./known_hosts:/app/known_hosts
      - ./id_rsa:/app/id_rsa
    restart: always
    networks:
      - proxied

networks:
  proxied:
    external:
      name: proxied
