version: "3.7"
services:
  shortener:
    image: ghcr.io/astridyu/aay-tw-shortener:main
    hostname: aay_tw
    expose:
      - 8000
    environment:
      TARGET_URL: https://astrid.tech
    restart: always
    networks:
      - proxied

networks:
  proxied:
    external:
      name: proxied
