apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
  namespace: metrics
  labels:
    app: grafana-storage
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs4/grafana
    server: "192.168.1.110"
