- name: Create Ansible user
  ansible.builtin.user:
    name: ansible
    comment: Ansible
    state: present
    append: yes
    create_home: yes
    groups: wheel

- name: Add authorized key for Ansible
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ssh_public_key}}"

- name: Allow ansible user to use sudo without a password
  ansible.builtin.copy:
    src: ansible-sudo
    dest: /etc/sudoers.d/ansible
    mode: "600"
