- name: Open firewall ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 5001
    ctstate: NEW
    jump: ACCEPT
    comment: iperf
- name: Install iperf
  ansible.builtin.apt:
    name:
      - iperf
    update_cache: yes
    cache_valid_time: 3600
    state: latest
