version: '3.8'

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"

  akkoma_db:
    image: postgres:12.1-alpine
    container_name: akkoma_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "akkoma"]
    environment:
      POSTGRES_USER: akkoma
      POSTGRES_PASSWORD: "${AKKOMA_DB_PASSWORD}"
      POSTGRES_DB: akkoma
    volumes:
      - akkoma_db_data:/var/lib/postgresql/data

  akkoma:
    image: ghcr.io/astridyu/akkoma:akkoma
    container_name: akkoma_web
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider --proxy=off localhost:4000 || exit 1",
        ]
    restart: unless-stopped
    volumes:
      - ./config-override.exs:/etc/akkoma/config.exs:ro
    env_file:
      - /etc/labnotes.env
    environment:
      DOMAIN: labnotes.astrid.tech
      INSTANCE_NAME: "Astrid's Laboratory"
      ADMIN_EMAIL: astrid@astrid.tech
      NOTIFY_EMAIL: astrid@astrid.tech
      DB_HOST: akkoma_db
      DB_USER: akkoma
      DB_PASS: "${AKKOMA_DB_PASSWORD}"
      DB_NAME: akkoma
    depends_on:
      - akkoma_db

volumes:
  akkoma_db_data:

