- name: Add authorized key from URL
  ansible.builtin.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: https://raw.githubusercontent.com/astralbijection/infra/main/ssh_keys/gh_rsa.pub
