- name: Calculate SSH keys path
  ansible.builtin.set_fact:
    ssh_keys_path: "{{ role_path }}/../../../ssh_keys"

- name: Find public keys to authorize
  connection: local
  shell: ls {{ ssh_keys_path }}/users/astrid/*.pub {{ ssh_keys_path }}/users/github/*.pub  
  register: to_authorize

- name: Find public keys to revoke
  connection: local
  shell: ls {{ ssh_keys_path }}/deprecated/*.pub
  register: to_revoke

- name: Authorize active keys
  ansible.builtin.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_items: "{{ to_authorize.stdout_lines }}"

- name: Revoke deprecated keys
  ansible.builtin.authorized_key:
    user: "{{ ssh_user }}"
    state: absent
    key: "{{ lookup('file', item) }}"
  with_items: "{{ to_revoke.stdout_lines }}"

