version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# Using https://github.com/chriscrowe/docker-pihole-unbound/blob/master/one-container/docker-compose.yaml
services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: dns
    domainname: dns.cloud.astrid.tech
    network_mode: host
    environment:
      TZ: "America/Los_Angeles"
      ServerIP: 192.168.8.8
      DNS1: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNS2: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
    env_file:
      - ./.env
    volumes:
      - "./whitelist.sh:/etc/cont-init.d/90-whitelist.sh:ro"
      - "./custom.list:/etc/pihole/custom.list:ro"
      #- "./05-ttl.conf:/etc/dnsmasq.d/05-ttl.conf:ro"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    hostname: node-exporter
    container_name: node-exporter
    volumes:
      - /:/rootfs:ro,rslave
    network_mode: host
    pid: host
    command:
      - "--path.rootfs=/rootfs"
    restart: unless-stopped
    ports:
      - 9100:9100
