# Following https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_11_Bullseye
- name: Install required utilities
  ansible.builtin.apt:
    cache_valid_time: 3600
    state: present
    name:
      - gnupg

- name: Trust Proxmox GPG key
  ansible.builtin.apt_key:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    state: present

- name: Replace sources with Proxmox
  ansible.builtin.apt_repository:
    filename: pve
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    mode: "644"

- name: Full upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full

- name: Install Proxmox
  ansible.builtin.apt:
    cache_valid_time: 3600
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
      - zfsutils-linux

- name: Remove unnecessary utilities
  ansible.builtin.apt:
    name: os-prober
    state: absent
