- name: Change hostname
  ansible.builtin.hostname:
    name: "{{short_hostname}}"

- name: Alter /etc/hosts with new hostname
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "644"

- name: Create new connection definition
  ansible.builtin.template:
    src: static.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/{{ interface }}.nmconnection
    mode: "600"

- name: Reboot without status check
  shell: reboot
  async: 1
  poll: 0
