version: "3.7"
services:
  db:
    image: postgres:13.1
    env_file:
      - .env.prod
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
    networks:
      - apinet

  api:
    image: astridyu/astrid_tech_api:latest
    hostname: astrid_tech
    depends_on:
      - db
    command: >
      bash -c "
        pipenv run python3 manage.py collectstatic --noinput &&
        pipenv run python3 manage.py migrate --database default &&
        pipenv run gunicorn astrid_tech.wsgi:application --bind 0.0.0.0:8001
      "
    env_file:
      - .env.prod
    environment:
      ASTRID_TECH_API_HOST: api.astrid.tech
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    expose:
      - "8001"
    volumes:
      - ./logs:/app/logs
      - ../caddy/www/astrid_tech/media:/app/media/
      - ../caddy/www/astrid_tech/static:/app/staticfiles/
    restart: always
    networks:
      - proxied
      - apinet

networks:
  apinet:
  proxied:
    external:
      name: proxied
