- name: Remove Proxmox enterprise repos
  hosts: proxmox
  tasks:
    - name: Remove repos
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent
    - name: Update
      ansible.builtin.apt:
        update_cache: yes
