apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
configMapGenerator:
  - name: synapse-configs
    files:
      - configs/homeserver.yaml
      - configs/log.config

  - name: db-init
    files:
      - db/init.sql

    # Needed because database can only be configured via special YAML.
  - name: homeserver-yaml-generator
    files:
      - configs/generate-homeserver-yaml.sh

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: synapse-secrets
    files:
      - configs/secrets.yaml
      - configs/signing.key

resources:
  - database.yaml
  - pvc.yaml
  - synapse.yaml
  - element.yaml
