- name: Convert bongus into a hypervisor
  become: true
  hosts: bongus.hv.astrid.tech
  roles:
    - name: lxc_server
      vars: 
        machbr_address: 10.1.2.1/24
        storage_pool_size: 4GB
    - name: kvm_server
  