- name: Install KVM
  become: true
  hosts: kvm_host
  roles:
    - kvm_server

- name: Install Podman
  become: true
  hosts: podman_host
  roles:
    - podman_server
  
- name: Install LXC 
  become: true
  hosts: lxc_host
  roles:
    - lxc_server
