config:
  core.https_address: 192.168.5.2:8443
  core.trust_password: foobar
networks: []
storage_pools:
  - config:
      size: 5GB
    description: ""
    name: local
    driver: btrfs
profiles:
  - config: {}
    description: ""
    devices:
      root:
        path: /
        pool: local
        type: disk
    name: default
projects: []
cluster:
  server_name: bongus
  enabled: true
  member_config: []
  cluster_address: ""
  cluster_certificate: ""
  server_address: ""
  cluster_password: ""
  cluster_certificate_path: ""
