grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.s.astrid.tech
    path: /

  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: grafana.s.astrid.tech

  persistence:
    type: pvc
    enabled: true
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    finalizers:
      - kubernetes.io/pvc-protection

  plugins:
    - grafana-worldmap-panel

prometheus:
  prometheusSpec:
    scrapeInterval: "10s"

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

    secrets:
      - prometheus-mc-basic-auth

    additionalScrapeConfigs:
      - job_name: external-node-exporter
        metrics_path: /metrics/node
        scheme: https
        basic_auth:
          username: prometheus
          password_file: /etc/prometheus/secrets/prometheus-mc-basic-auth/password
        static_configs:
          - targets:
              - mc.astrid.tech
            labels:
              nodetype: external

      - job_name: external-minecraft-exporter
        metrics_path: /metrics/minecraft
        scheme: https
        basic_auth:
          username: prometheus
          password_file: /etc/prometheus/secrets/prometheus-mc-basic-auth/password
        static_configs:
          - targets:
              - mc.astrid.tech
            labels:
              app: minecraft

      - job_name: external-caddy-exporter
        metrics_path: /metrics/caddy
        scheme: https
        basic_auth:
          username: prometheus
          password_file: /etc/prometheus/secrets/prometheus-mc-basic-auth/password
        static_configs:
          - targets:
              - mc.astrid.tech
            labels:
              app: caddy

      - job_name: external-fluent-bit-exporter
        metrics_path: /metrics/fluent-bit
        scheme: https
        basic_auth:
          username: prometheus
          password_file: /etc/prometheus/secrets/prometheus-mc-basic-auth/password
        static_configs:
          - targets:
              - mc.astrid.tech
            labels:
              app: fluent-bit

nodeExporter:
  extraArgs:
    - --collector.diskstats.ignored-devices=^(ram|loop|fd|(h|s|v)d[a-z]|nvme\\d+n\\d+p)\\d+$
    - --collector.thermal_zone
    - --collector.rapl
