repositories:
  - name: appscode
    url: https://charts.appscode.com/stable/
releases:
  - name: kubedb
    namespace: kube-system
    chart: appscode/kubedb
    installed: true
    version: v2021.03.17
    values:
      - name: global.license
        file: kubedb/license.txt
      - name: apiserver.enableValidatingWebhook
        value: "true"
      - name: apiserver.enableMutatingWebhook
        value: "true"