repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: freeipa-dns-sync
    namespace: external-dns
    chart: bitnami/external-dns
    installed: true
    values:
      - provider: rfc2136
        logFormat: json
        domainFilters:
          - s.astrid.tech
        rfc2136:
          host: ipa0.p.astrid.tech
          zone: s.astrid.tech
          tsigKeyname: k8s
          tsigSecretAlg: hmac-sha512
          secretName: freeipa-rfc2136

  - name: cloudflare-dns-proxied
    namespace: external-dns
    chart: bitnami/external-dns
    installed: true
    values:
      - provider: cloudflare
        logFormat: json
        domainFilters:
          - astrid.tech
        extraArgs:
          exclude-domains: s.astrid.tech
      - dns/cloudflare.secret.yaml
