# You can get the nightly results of these builds at
# https://nightly.link/astralbijection/infra/workflows/build-lxc-images/main

name: Build Customized NixOS ISO

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/build-nixos-iso.yml
      - nixos/*
      - flake.nix
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_nixos_iso:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          GC_DONT_GC=1 nix build --experimental-features "nix-command flakes" .#installer-iso 
          ln -s result/iso/*.iso nixos.iso

      - name: Upload image
        uses: actions/upload-artifact@v2.2.4
        with:
          name: nixos-installer
          path: nixos.iso
