# This is basically just a discount Hydra.

name: Build Nix targets

on:
  push: {}
  workflow_call: {}

jobs:
  calculate-matrix:
    name: Calculate build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: astralbijection
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Calculate build matrix
        run: |
          export target="github:astralbijection/infra/$GITHUB_SHA#gh-ci-matrix"
          echo "Building $target"
          GC_DONT_GC=1 nix build -o matrix.json $target

      - name: Set matrix output
        id: set-matrix
        run: |
          jq . matrix.json
          matrix=$(cat matrix.json)
          echo "::set-output name=matrix::$matrix"

  build-checks:
    name: "${{ matrix.target.target }}"
    needs: calculate-matrix
    runs-on: "${{ matrix.target.os }}"
    strategy:
      fail-fast: false
      # os/target pairs are written to target variable
      matrix: ${{ fromJson(needs.calculate-matrix.outputs.matrix) }}

    steps:
      - name: Remove unnecessary packages
        run: | # stolen from https://github.com/easimon/maximize-build-space
          echo "=== Before pruning ==="
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          echo
          echo "=== After pruning ==="
          df -h

      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux aarch64-darwin arm-linux
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: astralbijection
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build target
        run: |
          export target="github:astralbijection/infra/$GITHUB_SHA#${{ matrix.target.target }}"
          echo "Building $target"
          GC_DONT_GC=1 nix build --show-trace $target

