# This is basically just a discount Hydra.
# TODO: figure out aarch64 builds

name: Validate flake and build targets

on:
  push: {}
  workflow_call: {}

jobs:
  flake-check:
    name: Check Flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: astralbijection
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Validate Nix Flake
        run: GC_DONT_GC=1 nix flake check

      - name: Build CI items
        run: |
          GC_DONT_GC=1 nix build --experimental-features "nix-command flakes" ".#ci"

