name: Validate and Build Nix Flake

on:
  - push
  - pull_request

jobs:
  flake-check:
    name: Check Flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: astralbijection
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Validate Nix Flake
        run: GC_DONT_GC=1 nix flake check

  nixos-build:
    name: Build NixOS configurations
    runs-on: ubuntu-latest
    
    needs:
      - flake-check
    
    strategy:
      matrix:
        target:
          - bongus-hv
          - cracktop-pc
          - banana
          - jonathan-js
        
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: astralbijection
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install nixos-rebuild
        run: GC_DONT_GC=1 nix-env -i nixos-rebuild -f '<nixpkgs>'

      - name: Build nixos expression
        run: GC_DONT_GC=1 nixos-rebuild build --flake ".#${{ matrix.target }}"
